name: Run LoL Bot
on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install discord.py aiohttp

      - name: Install dependencies
        run: pip install discord.py aiohttp beautifulsoup4

      - name: Run Bot
        env:
          # 봇 코드(bot.py)에서 os.getenv("DISCORD_TOKEN")로 부르고 있으므로 왼쪽 이름이 같아야 함
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          # 봇 코드(bot.py)에서 os.getenv("RIOT_API_KEY")로 부르고 있으므로 왼쪽 이름이 같아야 함
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        run: python bot.py
